import type { Theme } from "../types";

// Nothing OS: a monochrome void, one red signal, code that lights up.
//
// The chrome identity lives in structure, not colour: 2px solid rules, square
// corners and square pills, uppercase tracked chrome labels, glyph icons, no
// shadow, no blur. The ansi palette stays near-monochrome so the terminal
// holds the void, and the surfaces that carry meaning carry hue: every
// `syntax` and `status` role is pinned rather than derived, on one four lamp
// palette (red keywords and deletions, amber numbers and edits, green strings
// and additions, cyan callables and renames) over neutral variables,
// properties and operators. `emphasis.strong` at 100%
// keeps the chrome from drawing its rules at 60% alpha, and `border` is
// softened against the dotted-era value so a continuous 2px line lands at the
// weight the dots used to.
export const nothing: Theme = {
  id: "nothing",
  name: "Nothing",
  description: "Monochrome void, hard rules, one red signal.",
  variants: {
    dark: {
      colors: {
        background: "#0a0a0a",
        foreground: "#ededeb",
        card: "#141414",
        cardForeground: "#ededeb",
        popover: "#1a1a1a",
        popoverForeground: "#ededeb",
        primary: "#d63b2e",
        primaryForeground: "#ffffff",
        secondary: "#1a1a1a",
        secondaryForeground: "#ededeb",
        muted: "#141414",
        mutedForeground: "#9a9a96",
        accent: "#1f1f1f",
        accentForeground: "#ededeb",
        destructive: "#d63b2e",
        border: "#5a5a56",
        input: "#5a5a56",
        ring: "#d63b2e",
        radius: "2px",
        borderStyle: "solid",
      },
      emphasis: {
        faint: "12%",
        subtle: "32%",
        soft: "45%",
        medium: "60%",
        strong: "100%",
        bold: "100%",
      },
      terminal: {
        background: "#0a0a0a",
        foreground: "#ededeb",
        cursor: "#d63b2e",
        cursorAccent: "#ffffff",
        selection: "rgba(214, 59, 46, 0.30)",
        ansi: [
          "#1e1e1e",
          "#e5342a",
          "#b6b6b3",
          "#d2cfc7",
          "#909aa2",
          "#c0b7bc",
          "#a8afaf",
          "#e8e8e6",
          "#7a7a76",
          "#ff5347",
          "#cfcfcc",
          "#e9e6dc",
          "#a9afb9",
          "#d8ced3",
          "#bfc7c7",
          "#ffffff",
        ],
      },
      syntax: {
        comment: "#6e6e6a",
        keyword: "#ff4b3e",
        string: "#5fd48a",
        number: "#ffb454",
        constant: "#ff8f6b",
        func: "#45cbe6",
        variable: "#ededeb",
        property: "#cfcfcb",
        gutterFg: "#63635e",
        type: "#8fd8e0",
        operator: "#9a9a96",
        tag: "#ff4b3e",
        tagBracket: "#6e6e6a",
        attr: "#ffb454",
        attrValue: "#5fd48a",
        heading: "#ff4b3e",
        link: "#62d0e8",
        invalid: "#ff5f56",
      },
      status: {
        added: "#5fd48a",
        modified: "#ffb454",
        deleted: "#ff4b3e",
        renamed: "#45cbe6",
        warning: "#ffcc4d",
        conflict: "#ff8f6b",
        ok: "#5fd48a",
      },
      shape: {
        frameWidth: "2px",
        frameRadius: "2px",
        chromeWidth: "2px",
        panelWidth: "2px",
        pillRadius: "2px",
      },
      type: { chromeTracking: "0.08em", chromeTransform: "uppercase" },
      effects: { shadow: "transparent", blur: "off" },
      icons: "nerd",
    },
    light: {
      colors: {
        background: "#fafaf9",
        foreground: "#0a0a0a",
        card: "#ffffff",
        cardForeground: "#0a0a0a",
        popover: "#ffffff",
        popoverForeground: "#0a0a0a",
        primary: "#c8342a",
        primaryForeground: "#ffffff",
        secondary: "#f0f0ee",
        secondaryForeground: "#0a0a0a",
        muted: "#f0f0ee",
        mutedForeground: "#5c5c58",
        accent: "#eaeae8",
        accentForeground: "#0a0a0a",
        destructive: "#c8342a",
        border: "#9e9e9a",
        input: "#9e9e9a",
        ring: "#c8342a",
        radius: "2px",
        borderStyle: "solid",
      },
      emphasis: {
        faint: "12%",
        subtle: "32%",
        soft: "45%",
        medium: "60%",
        strong: "100%",
        bold: "100%",
      },
      terminal: {
        background: "#fafaf9",
        foreground: "#0a0a0a",
        cursor: "#c8342a",
        cursorAccent: "#ffffff",
        selection: "rgba(200, 52, 42, 0.22)",
        ansi: [
          "#0a0a0a",
          "#c42419",
          "#55554f",
          "#6e6a5c",
          "#4a5058",
          "#6a5a60",
          "#56605e",
          "#2e2e2a",
          "#6e6e68",
          "#e5342a",
          "#74746e",
          "#8a8578",
          "#6a7280",
          "#8a7a82",
          "#78827e",
          "#141414",
        ],
      },
      syntax: {
        comment: "#6e6e68",
        keyword: "#c8241a",
        string: "#1f7a4d",
        number: "#8a5a00",
        constant: "#a8461c",
        func: "#0e6b7d",
        variable: "#0a0a0a",
        property: "#3a3a36",
        gutterFg: "#808079",
        type: "#2c6f77",
        operator: "#4a4a46",
        tag: "#c8241a",
        tagBracket: "#6e6e68",
        attr: "#8a5a00",
        attrValue: "#1f7a4d",
        heading: "#c8241a",
        link: "#0e6b7d",
        invalid: "#c42419",
      },
      status: {
        added: "#1f7a4d",
        modified: "#8a5a00",
        deleted: "#c8241a",
        renamed: "#0e6b7d",
        warning: "#8a6a00",
        conflict: "#a8461c",
        ok: "#1f7a4d",
      },
      shape: {
        frameWidth: "2px",
        frameRadius: "2px",
        chromeWidth: "2px",
        panelWidth: "2px",
        pillRadius: "2px",
      },
      type: { chromeTracking: "0.08em", chromeTransform: "uppercase" },
      effects: { shadow: "transparent", blur: "off" },
      icons: "nerd",
    },
  },
};
