import type { Theme } from "../types";

export const nothing: Theme = {
  id: "nothing",
  name: "Nothing",
  description:
    "Nothing OS-inspired theme with monochrome surfaces, dot-matrix typography, and red accents.",
  editorTheme: {
    light: "github-light",
    dark: "kanagawa",
  },
  variants: {
    dark: {
      colors: {
        background: "#0a0a0a",
        foreground: "#f0efe9",
        card: "#141412",
        cardForeground: "#f0efe9",
        popover: "#141412",
        popoverForeground: "#f0efe9",
        primary: "#c23b2e",
        primaryForeground: "#ffffff",
        secondary: "#1e1e1b",
        secondaryForeground: "#e0e0da",
        muted: "#232320",
        mutedForeground: "#8c8c86",
        accent: "#1a1a17",
        accentForeground: "#f0efe9",
        destructive: "#c23b2e",
        border: "#232320",
        input: "#232320",
        ring: "#c23b2e",
        radius: "0.375rem",
        sidebar: "#0a0a0a",
        sidebarForeground: "#f0efe9",
        sidebarPrimary: "#c23b2e",
        sidebarPrimaryForeground: "#ffffff",
        sidebarAccent: "#1a1a17",
        sidebarAccentForeground: "#f0efe9",
        sidebarBorder: "#232320",
        sidebarRing: "#c23b2e",
      },
      terminal: {
        background: "#0a0a0a",
        foreground: "#f0efe9",
        cursor: "#c23b2e",
        cursorAccent: "#0a0a0a",
        selection: "rgba(194, 59, 46, 0.3)",
        ansi: [
          "#1e1e1b",
          "#c23b2e",
          "#6a9c8a",
          "#e0b84a",
          "#5a8fc2",
          "#a878b0",
          "#6a9c9c",
          "#c8c8c2",
          "#8c8c86",
          "#d94b3d",
          "#7dae9b",
          "#ebd06a",
          "#6ca2d4",
          "#b98bc1",
          "#7daeae",
          "#f0efe9",
        ],
      },
      shape: {
        frameWidth: "1px",
        frameRadius: "8px",
        chromeWidth: "1px",
        panelWidth: "1px",
      },
      type: {
        sans: "'Inter Variable', -apple-system, sans-serif",
        display: "'DotGothic16', monospace",
        chromeTracking: "0.05em",
        chromeTransform: "uppercase",
        fonts: ["dotgothic16"],
      },
    },
    light: {
      colors: {
        background: "#f4f4f0",
        foreground: "#141412",
        card: "#e8e8e2",
        cardForeground: "#141412",
        popover: "#e8e8e2",
        popoverForeground: "#141412",
        primary: "#c23b2e",
        primaryForeground: "#ffffff",
        secondary: "#d8d8d2",
        secondaryForeground: "#141412",
        muted: "#e0e0da",
        mutedForeground: "#6c6c66",
        accent: "#deded8",
        accentForeground: "#141412",
        destructive: "#c23b2e",
        border: "#d4d4cd",
        input: "#d4d4cd",
        ring: "#c23b2e",
        radius: "0.375rem",
        sidebar: "#f4f4f0",
        sidebarForeground: "#141412",
        sidebarPrimary: "#c23b2e",
        sidebarPrimaryForeground: "#ffffff",
        sidebarAccent: "#deded8",
        sidebarAccentForeground: "#141412",
        sidebarBorder: "#d4d4cd",
        sidebarRing: "#c23b2e",
      },
      terminal: {
        background: "#f4f4f0",
        foreground: "#141412",
        cursor: "#c23b2e",
        cursorAccent: "#ffffff",
        selection: "rgba(194, 59, 46, 0.2)",
        ansi: [
          "#e8e8e2",
          "#c23b2e",
          "#2e7d5b",
          "#b8860b",
          "#2b6cb0",
          "#805ad5",
          "#2c7a7b",
          "#2d3748",
          "#6c6c66",
          "#a82e23",
          "#236347",
          "#966d09",
          "#22548a",
          "#6b46c1",
          "#236162",
          "#141412",
        ],
      },
      shape: {
        frameWidth: "1px",
        frameRadius: "8px",
        chromeWidth: "1px",
        panelWidth: "1px",
      },
      type: {
        sans: "'Inter Variable', -apple-system, sans-serif",
        display: "'DotGothic16', monospace",
        chromeTracking: "0.05em",
        chromeTransform: "uppercase",
        fonts: ["dotgothic16"],
      },
    },
  },
};
