import type { Theme } from "../types";

// Nothing OS: a monochrome void, one red signal, dots you can see.
//
// The identity lives in structure, not colour: a 2px dotted frame and dotted
// dividers, square corners and square pills, uppercase tracked chrome labels,
// glyph icons, no wallpaper, no shadow, no blur. Red is the only saturated
// colour on screen. The ansi palette is near-monochrome so the derived editor
// palette stays monochrome too, and `syntax.tag` is pinned off slot 1 so tags
// do not fire the signal in every file. `emphasis.strong` at 100% keeps the
// chrome from drawing its dotted rules at 60% alpha, where the dots vanish.
export const nothing: Theme = {
  id: "nothing",
  name: "Nothing",
  description: "Monochrome void, dotted rules, one red signal.",
  variants: {
    dark: {
      colors: {
        background: "#0a0a0a",
        foreground: "#ededeb",
        card: "#141414",
        cardForeground: "#ededeb",
        popover: "#1a1a1a",
        popoverForeground: "#ededeb",
        primary: "#d63b2e",
        primaryForeground: "#ffffff",
        secondary: "#1a1a1a",
        secondaryForeground: "#ededeb",
        muted: "#141414",
        mutedForeground: "#9a9a96",
        accent: "#1f1f1f",
        accentForeground: "#ededeb",
        destructive: "#d63b2e",
        border: "#6e6e6a",
        input: "#6e6e6a",
        ring: "#d63b2e",
        radius: "2px",
        borderStyle: "dotted",
      },
      emphasis: {
        faint: "12%",
        subtle: "32%",
        soft: "45%",
        medium: "60%",
        strong: "100%",
        bold: "100%",
      },
      terminal: {
        background: "#0a0a0a",
        foreground: "#ededeb",
        cursor: "#d63b2e",
        cursorAccent: "#ffffff",
        selection: "rgba(214, 59, 46, 0.30)",
        ansi: [
          "#1e1e1e", "#e5342a", "#b6b6b3", "#d2cfc7",
          "#909aa2", "#c0b7bc", "#a8afaf", "#e8e8e6",
          "#7a7a76", "#ff5347", "#cfcfcc", "#e9e6dc",
          "#a9afb9", "#d8ced3", "#bfc7c7", "#ffffff",
        ],
      },
      syntax: { tag: "#a8afaf" },
      shape: {
        frameWidth: "2px",
        frameRadius: "2px",
        chromeWidth: "2px",
        panelWidth: "2px",
        pillRadius: "2px",
      },
      type: { chromeTracking: "0.08em", chromeTransform: "uppercase" },
      effects: { shadow: "transparent", blur: "off", wallpaper: false },
      icons: "nerd",
    },
    light: {
      colors: {
        background: "#fafaf9",
        foreground: "#0a0a0a",
        card: "#ffffff",
        cardForeground: "#0a0a0a",
        popover: "#ffffff",
        popoverForeground: "#0a0a0a",
        primary: "#c8342a",
        primaryForeground: "#ffffff",
        secondary: "#f0f0ee",
        secondaryForeground: "#0a0a0a",
        muted: "#f0f0ee",
        mutedForeground: "#5c5c58",
        accent: "#eaeae8",
        accentForeground: "#0a0a0a",
        destructive: "#c8342a",
        border: "#8a8a86",
        input: "#8a8a86",
        ring: "#c8342a",
        radius: "2px",
        borderStyle: "dotted",
      },
      emphasis: {
        faint: "12%",
        subtle: "32%",
        soft: "45%",
        medium: "60%",
        strong: "100%",
        bold: "100%",
      },
      terminal: {
        background: "#fafaf9",
        foreground: "#0a0a0a",
        cursor: "#c8342a",
        cursorAccent: "#ffffff",
        selection: "rgba(200, 52, 42, 0.22)",
        ansi: [
          "#0a0a0a", "#c42419", "#55554f", "#6e6a5c",
          "#4a5058", "#6a5a60", "#56605e", "#2e2e2a",
          "#6e6e68", "#e5342a", "#74746e", "#8a8578",
          "#6a7280", "#8a7a82", "#78827e", "#141414",
        ],
      },
      syntax: { tag: "#56605e" },
      shape: {
        frameWidth: "2px",
        frameRadius: "2px",
        chromeWidth: "2px",
        panelWidth: "2px",
        pillRadius: "2px",
      },
      type: { chromeTracking: "0.08em", chromeTransform: "uppercase" },
      effects: { shadow: "transparent", blur: "off", wallpaper: false },
      icons: "nerd",
    },
  },
};
