import type { Theme } from "../types";

// Stardew-style wooden UI: near-uniform warm parchment separated by dark brown
// outlines, rather than panels distinguished by value. The outline does the
// separating, so surfaces stay close in tone and the chrome stays thin: 4px on
// the window frame, 2px everywhere else, with a single light bevel ring reading
// as a carved highlight. Radius is 0 all the way out to the window corners.
//
// Terminal ANSI is tuned per variant against its own background: every normal
// slot clears 4.5:1 and every bright slot clears 3:1, with blue and cyan held
// apart in hue so diff and log output stays parseable.
export const retroPixel: Theme = {
  id: "retro-pixel",
  name: "Retro Pixel",
  description: "Wooden plate, carved bevels, pixel display type.",
  editorTheme: { light: "solarized-light", dark: "gruvbox-dark" },
  variants: {
    light: {
      colors: {
        background: "#b98450",
        foreground: "#3a2412",
        card: "#f2dfb4",
        cardForeground: "#3a2412",
        popover: "#f7e8c6",
        popoverForeground: "#3a2412",
        primary: "#b4602c",
        primaryForeground: "#fdf2d8",
        secondary: "#e2c48d",
        secondaryForeground: "#3a2412",
        muted: "#e2c48d",
        mutedForeground: "#6d4a2b",
        accent: "#e8b26a",
        accentForeground: "#3a2412",
        destructive: "#a83226",
        border: "#4a2c14",
        input: "#4a2c14",
        ring: "#d99a3c",
        sidebar: "#e8cf9e",
        sidebarForeground: "#3a2412",
        sidebarPrimary: "#b4602c",
        sidebarPrimaryForeground: "#fdf2d8",
        sidebarAccent: "#e8b26a",
        sidebarAccentForeground: "#3a2412",
        sidebarBorder: "#4a2c14",
        sidebarRing: "#d99a3c",
        radius: "0rem",
        borderStyle: "solid",
      },
      shape: {
        frameWidth: "4px",
        frameRadius: "0px",
        framePadding: "8px",
        chromeWidth: "2px",
        panelWidth: "2px",
        slotWidth: "2px",
        controlWidth: "2px",
        bevelWidth: "2px",
        bevelOuter: "#f7e8c6",
        bevelMid: "transparent",
        bevelInner: "transparent",
        liftColor: "#5a3a1a",
        liftDepth: "2px",
      },
      type: {
        sans: "'Pixelify Sans', 'Inter Variable', sans-serif",
        display: "'Pixelify Sans', 'Inter Variable', sans-serif",
        chromeTracking: "0.04em",
        chromeTransform: "uppercase",
        fonts: ["pixelify-sans"],
      },
      terminal: {
        background: "#f7e8c6",
        foreground: "#3a2412",
        cursor: "#b4602c",
        cursorAccent: "#f7e8c6",
        selection: "rgba(180,96,44,0.28)",
        ansi: [
          "#2b1a0c", "#a3271d", "#41601a", "#7d5108",
          "#1e4f82", "#8c3168", "#146460", "#5f452a",
          "#77593f", "#c2402f", "#527a22", "#96650e",
          "#2e6fb5", "#b04486", "#187872", "#3a2412",
        ],
      },
    },
    dark: {
      colors: {
        background: "#2e1c0e",
        foreground: "#ecd7a8",
        card: "#40270f",
        cardForeground: "#f2e0b4",
        popover: "#4a2f14",
        popoverForeground: "#f2e0b4",
        primary: "#d98f45",
        primaryForeground: "#2e1c0e",
        secondary: "#5c3a1a",
        secondaryForeground: "#f2e0b4",
        muted: "#5c3a1a",
        mutedForeground: "#bb9464",
        accent: "#6d4720",
        accentForeground: "#f7ecd0",
        destructive: "#d9503f",
        border: "#8a5f30",
        input: "#8a5f30",
        ring: "#e0a84e",
        sidebar: "#241509",
        sidebarForeground: "#ecd7a8",
        sidebarPrimary: "#d98f45",
        sidebarPrimaryForeground: "#2e1c0e",
        sidebarAccent: "#6d4720",
        sidebarAccentForeground: "#f7ecd0",
        sidebarBorder: "#8a5f30",
        sidebarRing: "#e0a84e",
        radius: "0rem",
        borderStyle: "solid",
      },
      shape: {
        frameWidth: "4px",
        frameRadius: "0px",
        framePadding: "8px",
        chromeWidth: "2px",
        panelWidth: "2px",
        slotWidth: "2px",
        controlWidth: "2px",
        bevelWidth: "2px",
        bevelOuter: "#8a5f30",
        bevelMid: "transparent",
        bevelInner: "transparent",
        liftColor: "#150c05",
        liftDepth: "2px",
      },
      type: {
        sans: "'Pixelify Sans', 'Inter Variable', sans-serif",
        display: "'Pixelify Sans', 'Inter Variable', sans-serif",
        chromeTracking: "0.04em",
        chromeTransform: "uppercase",
        fonts: ["pixelify-sans"],
      },
      // Recessed below the app background so the terminal reads as an inset
      // slot, with the ink pushed brighter and more saturated than the chrome
      // browns: a warm-on-warm terminal goes hazy fast.
      terminal: {
        background: "#191410",
        foreground: "#f5e3ba",
        cursor: "#e0a84e",
        cursorAccent: "#191410",
        selection: "rgba(217,143,69,0.32)",
        ansi: [
          "#2a1a0c", "#f0685a", "#9ac356", "#eec052",
          "#74b0e2", "#dc8ec2", "#6cc9bf", "#e3cfa5",
          "#ac8558", "#ff9086", "#bde383", "#ffdf88",
          "#a3d0f5", "#f2b4da", "#9ae8dd", "#fff6e0",
        ],
      },
    },
  },
};
