import type { Theme } from "../types";

// Wood-plate palette from the Terra Retro Pixel UI reference: cream slots on a
// tan panel, four ink tones stacked into the frame bevel. Radius stays 0 and
// the bevel does the work that a shadow would do in a soft theme.
export const retroPixel: Theme = {
  id: "retro-pixel",
  name: "Retro Pixel",
  description: "Wooden plate, heavy ink bevels, pixel display type.",
  editorTheme: { light: "solarized-light", dark: "solarized-light" },
  variants: {
    light: {
      colors: {
        background: "#deb887",
        foreground: "#4a2d16",
        card: "#f4e4bc",
        cardForeground: "#4a2d16",
        popover: "#f4e4bc",
        popoverForeground: "#4a2d16",
        primary: "#c76b3c",
        primaryForeground: "#f4e4bc",
        secondary: "#c9a366",
        secondaryForeground: "#3a230f",
        muted: "#c9a366",
        mutedForeground: "#8a6a4a",
        accent: "#c9a366",
        accentForeground: "#3a230f",
        destructive: "#c0392b",
        border: "#4a2d16",
        input: "#6b4226",
        ring: "#c76b3c",
        sidebar: "#deb887",
        sidebarForeground: "#4a2d16",
        sidebarPrimary: "#c76b3c",
        sidebarPrimaryForeground: "#f4e4bc",
        sidebarAccent: "#c9a366",
        sidebarAccentForeground: "#3a230f",
        sidebarBorder: "#4a2d16",
        sidebarRing: "#c76b3c",
        radius: "0rem",
        borderStyle: "solid",
      },
      shape: {
        frameWidth: "8px",
        chromeWidth: "6px",
        panelWidth: "4px",
        slotWidth: "4px",
        controlWidth: "3px",
        bevelWidth: "4px",
        bevelOuter: "#8a5a2e",
        bevelMid: "#6b4226",
        bevelInner: "#4a2d16",
        liftColor: "#2a1a0d",
        liftDepth: "6px",
      },
      type: {
        sans: "'VT323', monospace",
        mono: "'VT323', monospace",
        display: "'Press Start 2P', monospace",
        chromeTracking: "1px",
        chromeTransform: "uppercase",
        fonts: ["press-start-2p", "vt323"],
      },
      terminal: {
        background: "#f4e4bc",
        foreground: "#4a2d16",
        cursor: "#4a2d16",
        cursorAccent: "#f4e4bc",
        selection: "rgba(199,107,60,0.30)",
        ansi: [
          "#3a230f", "#c0392b", "#7a9a5a", "#c9a366",
          "#5a8a9a", "#8a5a2e", "#5a8a9a", "#8a6a4a",
          "#6b4226", "#d4553f", "#8fae6a", "#deb887",
          "#6fa0b0", "#a97c50", "#6fa0b0", "#f4e4bc",
        ],
      },
    },
    dark: {
      colors: {
        background: "#3a230f",
        foreground: "#deb887",
        card: "#4a2d16",
        cardForeground: "#f4e4bc",
        popover: "#4a2d16",
        popoverForeground: "#f4e4bc",
        primary: "#c76b3c",
        primaryForeground: "#241708",
        secondary: "#6b4226",
        secondaryForeground: "#f4e4bc",
        muted: "#6b4226",
        mutedForeground: "#a97c50",
        accent: "#6b4226",
        accentForeground: "#f4e4bc",
        destructive: "#c0392b",
        border: "#c9a366",
        input: "#a97c50",
        ring: "#c76b3c",
        sidebar: "#2a1a0d",
        sidebarForeground: "#deb887",
        sidebarPrimary: "#c76b3c",
        sidebarPrimaryForeground: "#241708",
        sidebarAccent: "#6b4226",
        sidebarAccentForeground: "#f4e4bc",
        sidebarBorder: "#c9a366",
        sidebarRing: "#c76b3c",
        radius: "0rem",
        borderStyle: "solid",
      },
      shape: {
        frameWidth: "8px",
        chromeWidth: "6px",
        panelWidth: "4px",
        slotWidth: "4px",
        controlWidth: "3px",
        bevelWidth: "4px",
        bevelOuter: "#8a5a2e",
        bevelMid: "#a97c50",
        bevelInner: "#c9a366",
        liftColor: "#1a1006",
        liftDepth: "6px",
      },
      type: {
        sans: "'VT323', monospace",
        mono: "'VT323', monospace",
        display: "'Press Start 2P', monospace",
        chromeTracking: "1px",
        chromeTransform: "uppercase",
        fonts: ["press-start-2p", "vt323"],
      },
      terminal: {
        background: "#3a230f",
        foreground: "#deb887",
        cursor: "#deb887",
        cursorAccent: "#3a230f",
        selection: "rgba(199,107,60,0.35)",
        ansi: [
          "#2a1a0d", "#c0392b", "#7a9a5a", "#c9a366",
          "#5a8a9a", "#a97c50", "#6fa0b0", "#deb887",
          "#6b4226", "#d4553f", "#8fae6a", "#e0c88a",
          "#7ab0c0", "#c79a6a", "#8ac4c4", "#f4e4bc",
        ],
      },
    },
  },
};
