import type { Theme } from "../types";

// Stardew-style wooden UI: near-uniform warm parchment separated by dark brown
// outlines, rather than panels distinguished by value. The outline does the
// separating, so surfaces stay close in tone and the chrome stays thin: 4px on
// the window frame, 2px everywhere else, with a single light bevel ring reading
// as a carved highlight. Radius is 0 all the way out to the window corners.
//
// Terminal ANSI is tuned per variant against its own background: every normal
// slot clears 4.5:1 and every bright slot clears 3:1, with blue and cyan held
// apart in hue so diff and log output stays parseable.
export const stardew: Theme = {
  id: "stardew",
  name: "Stardew",
  description: "Authentic Stardew Valley wooden plate, golden carved bevels, pixel type.",
  editorTheme: { light: "github-light", dark: "gruvbox-dark" },
  variants: {
    light: {
      colors: {
        background: "#f7e8c6",
        foreground: "#3a2412",
        card: "#e8cfa0",
        cardForeground: "#3a2412",
        popover: "#f7e8c6",
        popoverForeground: "#3a2412",
        primary: "#b4602c",
        primaryForeground: "#fdf2d8",
        secondary: "#e2c48d",
        secondaryForeground: "#3a2412",
        muted: "#e2c48d",
        mutedForeground: "#6d4a2b",
        accent: "#e8b26a",
        accentForeground: "#3a2412",
        destructive: "#a83226",
        border: "#4a2c14",
        input: "#4a2c14",
        ring: "#ffd46b",
        sidebar: "#e8cfa0",
        sidebarForeground: "#3a2412",
        sidebarPrimary: "#b4602c",
        sidebarPrimaryForeground: "#fdf2d8",
        sidebarAccent: "#e8b26a",
        sidebarAccentForeground: "#3a2412",
        sidebarBorder: "#4a2c14",
        sidebarRing: "#ffd46b",
        radius: "0.25rem",
        borderStyle: "solid",
      },
      shape: {
        frameWidth: "5px",
        frameRadius: "6px",
        framePadding: "6px",
        chromeWidth: "2px",
        panelWidth: "2px",
        slotWidth: "2px",
        controlWidth: "2px",
        bevelWidth: "2px",
        bevelOuter: "#ffd46b",
        bevelMid: "transparent",
        bevelInner: "transparent",
        liftColor: "#381303",
        liftDepth: "3px",
      },
      type: {
        sans: "'Pixelify Sans', 'Inter Variable', sans-serif",
        display: "'Pixelify Sans', 'Inter Variable', sans-serif",
        chromeTracking: "0.04em",
        chromeTransform: "uppercase",
        fonts: ["pixelify-sans"],
      },
      terminal: {
        background: "#f7e8c6",
        foreground: "#3a2412",
        cursor: "#b4602c",
        cursorAccent: "#f7e8c6",
        selection: "rgba(180,96,44,0.28)",
        ansi: [
          "#2b1a0c", "#a3271d", "#325816", "#7a4404",
          "#1a4675", "#7a2559", "#0e5652", "#5f452a",
          "#6e4f32", "#941f16", "#284d12", "#6e3d02",
          "#143d68", "#681c4c", "#094a46", "#3a2412",
        ],
      },
    },
    dark: {
      colors: {
        background: "#2b1104",
        foreground: "#ffcd9b",
        card: "#481f08",
        cardForeground: "#ffcd9b",
        popover: "#54250a",
        popoverForeground: "#ffcd9b",
        primary: "#d96b27",
        primaryForeground: "#2b1104",
        secondary: "#662f0f",
        secondaryForeground: "#ffcd9b",
        muted: "#662f0f",
        mutedForeground: "#c4905e",
        accent: "#7d3c16",
        accentForeground: "#ffe3c2",
        destructive: "#d9503f",
        border: "#8c3a0e",
        input: "#8c3a0e",
        ring: "#ffd46b",
        sidebar: "#200c02",
        sidebarForeground: "#ffcd9b",
        sidebarPrimary: "#d96b27",
        sidebarPrimaryForeground: "#2b1104",
        sidebarAccent: "#7d3c16",
        sidebarAccentForeground: "#ffe3c2",
        sidebarBorder: "#8c3a0e",
        sidebarRing: "#ffd46b",
        radius: "0.25rem",
        borderStyle: "solid",
      },
      shape: {
        frameWidth: "5px",
        frameRadius: "6px",
        framePadding: "6px",
        chromeWidth: "2px",
        panelWidth: "2px",
        slotWidth: "2px",
        controlWidth: "2px",
        bevelWidth: "2px",
        bevelOuter: "#ffd46b",
        bevelMid: "transparent",
        bevelInner: "transparent",
        liftColor: "#150c05",
        liftDepth: "3px",
      },
      type: {
        sans: "'Pixelify Sans', 'Inter Variable', sans-serif",
        display: "'Pixelify Sans', 'Inter Variable', sans-serif",
        chromeTracking: "0.04em",
        chromeTransform: "uppercase",
        fonts: ["pixelify-sans"],
      },
      terminal: {
        background: "#231005",
        foreground: "#f5e3ba",
        cursor: "#e0a84e",
        cursorAccent: "#231005",
        selection: "rgba(217,143,69,0.32)",
        ansi: [
          "#2a1a0c", "#f0685a", "#9ac356", "#eec052",
          "#74b0e2", "#dc8ec2", "#6cc9bf", "#e3cfa5",
          "#ac8558", "#ff9086", "#bde383", "#ffdf88",
          "#a3d0f5", "#f2b4da", "#9ae8dd", "#fff6e0",
        ],
      },
    },
  },
};
