import type { Theme } from "../types";

// Editorial wireframe: achromatic chrome, hairline grid borders, square
// corners (radius 0). The ANSI slots carry a trace of chroma on purpose. A
// fully greyscale palette would leave git diffs and error output unreadable,
// which costs more than the last few percent of fidelity is worth.
export const wireframe: Theme = {
  id: "wireframe",
  name: "Wireframe",
  description: "Achromatic grid and hairline rules; square corners, ink on paper.",
  editorTheme: { dark: "github-dark", light: "github-light" },
  variants: {
    light: {
      colors: {
        background: "#f5f5f5",
        foreground: "#0d0d0d",
        card: "#fbfbfb",
        cardForeground: "#0d0d0d",
        popover: "#fbfbfb",
        popoverForeground: "#0d0d0d",
        primary: "#0d0d0d",
        primaryForeground: "#f5f5f5",
        secondary: "#e8e8e8",
        secondaryForeground: "#0d0d0d",
        muted: "#e8e8e8",
        mutedForeground: "#6b6b6b",
        accent: "#dedede",
        accentForeground: "#0d0d0d",
        destructive: "#9c3d33",
        border: "rgba(13,13,13,0.62)",
        input: "rgba(13,13,13,0.75)",
        ring: "#0d0d0d",
        sidebar: "#efefef",
        sidebarForeground: "#0d0d0d",
        sidebarPrimary: "#0d0d0d",
        sidebarPrimaryForeground: "#f5f5f5",
        sidebarAccent: "#dedede",
        sidebarAccentForeground: "#0d0d0d",
        sidebarBorder: "rgba(13,13,13,0.62)",
        sidebarRing: "#0d0d0d",
        radius: "0rem",
      },
      terminal: {
        cursor: "#0d0d0d",
        cursorAccent: "#f5f5f5",
        selection: "rgba(13,13,13,0.18)",
        ansi: [
          "#0d0d0d", "#8f3f34", "#4a5f42", "#7d6a3c",
          "#3f4f6b", "#6b4560", "#3f6169", "#6b6b6b",
          "#9a9a9a", "#b0554a", "#5f7a55", "#9c8550",
          "#556a8c", "#8a5c7d", "#547f88", "#0d0d0d",
        ],
      },
    },
    dark: {
      colors: {
        background: "#0d0d0d",
        foreground: "#ededed",
        card: "#151515",
        cardForeground: "#ededed",
        popover: "#151515",
        popoverForeground: "#ededed",
        primary: "#ededed",
        primaryForeground: "#0d0d0d",
        secondary: "#1f1f1f",
        secondaryForeground: "#ededed",
        muted: "#1f1f1f",
        mutedForeground: "#8f8f8f",
        accent: "#2a2a2a",
        accentForeground: "#ededed",
        destructive: "#c25a4d",
        border: "rgba(237,237,237,0.5)",
        input: "rgba(237,237,237,0.62)",
        ring: "#ededed",
        sidebar: "#0a0a0a",
        sidebarForeground: "#ededed",
        sidebarPrimary: "#ededed",
        sidebarPrimaryForeground: "#0d0d0d",
        sidebarAccent: "#2a2a2a",
        sidebarAccentForeground: "#ededed",
        sidebarBorder: "rgba(237,237,237,0.5)",
        sidebarRing: "#ededed",
        radius: "0rem",
      },
      terminal: {
        cursor: "#ededed",
        cursorAccent: "#0d0d0d",
        selection: "rgba(237,237,237,0.2)",
        ansi: [
          "#151515", "#b3675c", "#7d9070", "#b09a6a",
          "#7185a3", "#9c7392", "#6f959d", "#b8b8b8",
          "#5c5c5c", "#cc8074", "#97ab89", "#c9b384",
          "#8b9ebb", "#b58cab", "#89aeb6", "#f5f5f5",
        ],
      },
    },
  },
};
