/**
 * Documentation for the token registry, one line per key.
 *
 * Kept beside `tokens.ts` rather than inside it because the only readers are
 * `pnpm theme:sync-tokens` and its test: prose that exists to generate
 * THEME.md has no business in the always-eager theme chunk. A token without
 * an entry here fails `tokens.test.ts`.
 */
export const TOKEN_DOCS: Readonly<Record<string, string>> = {
  "colors.background": "App canvas.",
  "colors.foreground": "Primary text on the canvas.",
  "colors.card": "Raised surface. Falls back to the canvas.",
  "colors.cardForeground": "Text on card surfaces.",
  "colors.popover": "Popover surface.",
  "colors.popoverForeground": "Text on popover surfaces.",
  "colors.primary": "Primary accent color.",
  "colors.primaryForeground": "Text on primary color.",
  "colors.secondary": "Secondary accent color.",
  "colors.secondaryForeground": "Text on secondary color.",
  "colors.muted": "Muted surface.",
  "colors.mutedForeground": "Text on muted surfaces.",
  "colors.accent": "Accent color.",
  "colors.accentForeground": "Text on accent color.",
  "colors.destructive": "Destructive action color.",
  "colors.border": "Default border color.",
  "colors.input": "Input border color.",
  "colors.ring": "Focus ring color.",
  "colors.radius": "Border radius.",
  "colors.borderStyle": "Border style.",
  "shape.frameWidth": "Frame border width.",
  "shape.frameRadius": "Frame border radius.",
  "shape.framePadding": "Frame padding.",
  "shape.chromeWidth": "Chrome border width.",
  "shape.panelWidth": "Panel border width.",
  "shape.slotWidth": "Slot border width.",
  "shape.bevelWidth": "Bevel width.",
  "shape.bevelOuter": "Bevel outer color.",
  "shape.bevelMid": "Bevel mid color.",
  "shape.bevelInner": "Bevel inner color.",
  "shape.spacing": "UI spacing.",
  "shape.pillRadius":
    "Radius of pills, chips, toggles, and badges (rounded-pill).",
  "effects.shadow":
    "Tint every shadow utility uses; transparent flattens the app.",
  "effects.blur": "Backdrop blur: on keeps the scale, off zeroes it.",
  "motion.speed":
    "Multiplier on every chrome duration; instant collapses them to a snap.",
  "motion.easing": "Curve shared by every entrance, exit and transition.",
  "type.chromeTracking": "Chrome letter spacing.",
  "type.chromeTransform": "Chrome text transform.",
  "terminal.background": "Terminal background.",
  "terminal.foreground": "Terminal foreground.",
  "terminal.cursor": "Terminal cursor.",
  "terminal.cursorAccent": "Terminal cursor accent.",
  "terminal.selection": "Terminal selection.",
  "terminal.ansiBlack": "ANSI Black.",
  "terminal.ansiRed": "ANSI Red.",
  "terminal.ansiGreen": "ANSI Green.",
  "terminal.ansiYellow": "ANSI Yellow.",
  "terminal.ansiBlue": "ANSI Blue.",
  "terminal.ansiMagenta": "ANSI Magenta.",
  "terminal.ansiCyan": "ANSI Cyan.",
  "terminal.ansiWhite": "ANSI White.",
  "terminal.ansiBrightBlack": "ANSI Bright Black.",
  "terminal.ansiBrightRed": "ANSI Bright Red.",
  "terminal.ansiBrightGreen": "ANSI Bright Green.",
  "terminal.ansiBrightYellow": "ANSI Bright Yellow.",
  "terminal.ansiBrightBlue": "ANSI Bright Blue.",
  "terminal.ansiBrightMagenta": "ANSI Bright Magenta.",
  "terminal.ansiBrightCyan": "ANSI Bright Cyan.",
  "terminal.ansiBrightWhite": "ANSI Bright White.",
  "syntax.comment": "Comment color.",
  "syntax.keyword": "Keyword color.",
  "syntax.string": "String color.",
  "syntax.number": "Number color.",
  "syntax.constant": "Constant color.",
  "syntax.func": "Function color.",
  "syntax.variable": "Variable color.",
  "syntax.property": "Property color.",
  "syntax.gutterFg": "Gutter foreground color.",
  "syntax.type": "Type color.",
  "syntax.operator": "Operator color.",
  "syntax.tag": "Tag color.",
  "syntax.tagBracket": "Tag bracket color.",
  "syntax.attr": "Attribute color.",
  "syntax.attrValue": "Attribute value color.",
  "syntax.heading": "Heading color.",
  "syntax.link": "Link color.",
  "syntax.invalid": "Invalid token color.",
  "status.added": "Added status color.",
  "status.modified": "Modified status color.",
  "status.deleted": "Deleted status color.",
  "status.renamed": "Renamed status color.",
  "status.warning": "Warning status color.",
  "status.conflict": "Conflict status color.",
  "status.ok": "OK status color.",
  "emphasis.faint": "Faint emphasis.",
  "emphasis.subtle": "Subtle emphasis.",
  "emphasis.soft": "Soft emphasis.",
  "emphasis.medium": "Medium emphasis.",
  "emphasis.strong": "Strong emphasis.",
  "emphasis.bold": "Bold emphasis.",
};
